general:
  epochs: 40
dataset:
  batch_size: 16
  num_workers: 0
  train_dogs_path: "./dataset/train/dogs/"
  train_cats_path: "./dataset/train/cats/"
  test_dogs_path: "./dataset/test/dogs/"
  test_cats_path: "./dataset/test/cats/"
test:
  batch_size: dataset.batch_size
  drop_last: False
  shuffle: False
train:
  batch_size: dataset.batch_size
  drop_last: True
  shuffle: True
optimizer:
  optimizer_type: torch.optim.Adam
  params:
    betas: [ 0.9, 0.999 ]
    lr: 0.0001
